#!/usr/bin/env ruby
	require_relative 'lib/input_formatter.rb'
	require_relative 'lib/pizza_bot.rb'

	input = InputFormatter.new('5x5 (0, 0) (1, 3) (4, 4) (4, 2) (4, 2) (0, 1) (3, 2) (2, 3) (4, 1)')
  puts input.error.empty? ? Pizzabot.new.delivery_instructions(input.grid, input.drops) : input.error
